blank_issues_enabled: true
contact_links:
  - name: "Telegram Chat"
    url: "https://t.me/torrentpier"
    about: >
      You can use our Telegram chat to ask support questions and for general discussions.
  - name: "Community Forum"
    url: "https://torrentpier.com"
    about: >
      You can use our forum for support questions which need more background information.
  - name: "Community Discussions on GitHub"
    url: "https://github.com/orgs/torrentpier/discussions"
    about: >
      You can use GitHub discussions for support questions which need more background information.
