name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install prerequisites
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libev-dev libmysql++-dev libtcmalloc-minimal4 
        version: 1.0
    - name: install boost
      uses: MarkusJx/install-boost@v1.0.1
      id: install-boost
      with:
        boost_version: 1.73.0
        platform_version: 22.04
        boost_install_dir: /home/runner/boost-lib
    - name: configure
      run: ./configure  --with-boost-libdir=${{ steps.install-boost.outputs.BOOST_ROOT }}
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
