name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install prerequisites
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libboost-dev libboost-iostreams-dev libboost-system-dev libev-dev libmysql++-dev libtcmalloc-minimal4 
        version: 1.0
    - name: autoreconf
      run: autoreconf
    - name: configure
      run: >
       ./configure
       --with-boost-libdir=/usr/lib/x86_64-linux-gnu
       --with-ev-lib=/usr/lib/x86_64-linux-gnu
       --with-mysql-lib=/usr/lib/x86_64-linux-gnu
       --with-mysqlpp-lib=/usr/lib/x86_64-linux-gnu
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
